---
### Author: Ally Sprik
### Last-updated: 25-02-2024

Goal of this notebook is to generate networks in a variety of TCGA configurations, without platelets

description: Create 4 different Bayesian Networks for the TCGA data
            1. POLE to LNM and PostoperativeGrade
            2. POLE to PostoperativeGrade and Recurrence
            3. POLE to LNM and Recurrence
            4. POLE to LNM, PostoperativeGrade and Recurrence
---

```{r}
library(bnlearn)
library(Rgraphviz)

# The necessary subsets are created in the data-cleaning.R
# Transform the modelstring (bayesian network) to Directed Acyclic Graph
# Define the model string for Dag_1
dag_1 = paste("[MyometrialInvasion|PostoperativeGrade]",#[MRI_MI|MyometrialInvasion]",
            "[Cytology|PostoperativeGrade]",
            "[PreoperativeGrade]",
            "[PostoperativeGrade|PreoperativeGrade]",
            "[FIGO|PostoperativeGrade]",
            "[LNM|LVSI:MyometrialInvasion:PostoperativeGrade:Chemotherapy]",
            "[CA125|LNM][CTMRI|LNM:CA125]",
            "[LVSI|PostoperativeGrade:Cytology:Chemotherapy]",
            "[p53|LNM:PostoperativeGrade:L1CAM]",
            "[ER|LNM:PostoperativeGrade][PR|LNM:PostoperativeGrade:ER]",
            "[L1CAM|LNM:PostoperativeGrade:PR]",
            "[MSI|LNM:PostoperativeGrade]",
            "[POLE|LNM:PostoperativeGrade]",
            "[Recurrence|CA125:LNM:LVSI:PostoperativeGrade]",
            "[Chemotherapy|PostoperativeGrade]",
            "[Radiotherapy|MyometrialInvasion]",
            "[Survival1yr|Recurrence:Chemotherapy:Radiotherapy:Survival3yr:Survival5yr]",
            "[Survival3yr|Recurrence:Chemotherapy:Radiotherapy:Survival5yr]",
            "[Survival5yr|Recurrence:Chemotherapy:Radiotherapy]", sep="")

# dagmodel: pre-defined directed acyclic graph (DAG) structure version 1
dagmodel = model2network(dag_1)

# Plot the Graphs
graphviz.plot(dagmodel, shape = "rectangle", highlight = list("nodes"))
```

# Import the data and and fit the model

```{r}
# Nodes in the model
nodesDag = names(dagmodel$nodes)

# Import the data
data = read.csv("0.1. Cleaned_data/Training_JAMA+Brno_model_cleaned.csv", header = TRUE, sep = ",", na.strings = c("NA", "N/A", "N/A ", " ", ""))

# Select only the rows that have yes in Included_in_training_cohort
#data = data[data$Included_in_training_cohort == "yes",]
# Select for nodes in model
data = as.data.frame(lapply(data[, nodesDag], as.factor))

```

# Fit the model

```{r}
# Fit the model
fittedModel = bn.fit(dagmodel, data = data, method = 'bayes')
fittedNet = bn.net(fittedModel)
imputedData = impute(fittedModel, data, method = "bayes-lw", n=5000)
fittedModeli = bn.fit(dagmodel, data = imputedData)

```
```{r}
# Load and insert CPTs
combined_MSI_POLE = read.csv("3. Model/CPT_files/MSI_POLE_combined.csv", header = TRUE, sep = ",")
combined_FIGO = read.csv("3. Model/CPT_files/FIGO_combined.csv", header = TRUE, sep = ",")

# Compute new MSI CPT
countMSI = xtabs(~ MSI + LNM + PostoperativeGrade, combined_MSI_POLE)
laplace_constant = 1
smoothed_countMSI = countMSI + laplace_constant
cptMSIsmoothed = prop.table(smoothed_countMSI, c(3, 2))

names(dimnames(cptMSIsmoothed)) = c("MSI", "LNM", "PostoperativeGrade")

fittedModeli$MSI = as.table(cptMSIsmoothed)

# Compute new POLE CPT
countPOLE = xtabs(~ POLE + LNM + PostoperativeGrade, combined_MSI_POLE)
laplace_constant = 1
smoothed_countPOLE = countPOLE + laplace_constant
cptPOLEsmoothed = prop.table(smoothed_countPOLE, c(3, 2))

names(dimnames(cptPOLEsmoothed)) = c("POLE", "LNM", "PostoperativeGrade")

fittedModeli$POLE = as.table(cptPOLEsmoothed)

# Compute new FIGO CPT
countFIGO = xtabs(~ FIGO + PostoperativeGrade, combined_FIGO)
laplace_constant = 1
smoothed_countFIGO = countFIGO + laplace_constant
cptFIGOsmoothed = prop.table(smoothed_countFIGO, 2)

names(dimnames(cptFIGOsmoothed)) = c("FIGO", "PostoperativeGrade")

fittedModeli$FIGO = as.table(cptFIGOsmoothed)

```
```{r}

# Plot the Graphs
graphviz.plot(fittedNet, shape = "rectangle", highlight = list("nodes"))
write.net("3. Model/Fitted_Networks/R_WOP_AddTCGA_1_fitted_952+Brno.net", fittedModeli)

```


Now for the second arrangement of the nodes

```{r}
# Define the model string for Dag_1
dag_2 = paste("[MyometrialInvasion|PostoperativeGrade]",#[MRI_MI|MyometrialInvasion]",
            "[Cytology|PostoperativeGrade]",
            "[PreoperativeGrade]",
            "[PostoperativeGrade|PreoperativeGrade]","[FIGO|PostoperativeGrade]",
            "[LNM|LVSI:MyometrialInvasion:PostoperativeGrade:Chemotherapy]",
            "[CA125|LNM][CTMRI|LNM:CA125]",
            "[LVSI|PostoperativeGrade:Cytology:Chemotherapy]",
            "[p53|LNM:PostoperativeGrade:L1CAM]",
            "[ER|LNM:PostoperativeGrade][PR|LNM:PostoperativeGrade:ER]",
            "[L1CAM|LNM:PostoperativeGrade:PR]",
            "[MSI|LNM:PostoperativeGrade]",
            "[POLE|Recurrence:PostoperativeGrade]",
            "[Recurrence|CA125:LNM:LVSI:PostoperativeGrade]",
            "[Chemotherapy|PostoperativeGrade]",
            "[Radiotherapy|MyometrialInvasion]",
            "[Survival1yr|Recurrence:Chemotherapy:Radiotherapy:Survival3yr:Survival5yr]",
            "[Survival3yr|Recurrence:Chemotherapy:Radiotherapy:Survival5yr]",
            "[Survival5yr|Recurrence:Chemotherapy:Radiotherapy]", sep="")

# dagmodel: pre-defined directed acyclic graph (DAG) structure version 1
dagmodel = model2network(dag_2)

# Plot the Graphs
graphviz.plot(dagmodel, shape = "rectangle", highlight = list("nodes"))


```


Fit the model

```{r}
# Fit the model
fittedModel = bn.fit(dagmodel, data = data, method = 'bayes')
fittedNet = bn.net(fittedModel)
imputedData = impute(fittedModel, data, method = "bayes-lw", n=5000)
fittedModeli = bn.fit(dagmodel, data = imputedData)
```
```{r}
# Load and insert CPTs
combined_MSI_POLE = read.csv("3. Model/CPT_files/MSI_POLE_combined.csv", header = TRUE, sep = ",")
combined_FIGO = read.csv("3. Model/CPT_files/FIGO_combined.csv", header = TRUE, sep = ",")

# Compute new MSI CPT
countMSI = xtabs(~ MSI + LNM + PostoperativeGrade, combined_MSI_POLE)
laplace_constant = 1
smoothed_countMSI = countMSI + laplace_constant
cptMSIsmoothed = prop.table(smoothed_countMSI, c(3, 2))

names(dimnames(cptMSIsmoothed)) = c("MSI", "LNM", "PostoperativeGrade")

fittedModeli$MSI = as.table(cptMSIsmoothed)

# Compute new POLE CPT
countPOLE = xtabs(~ POLE + LNM + PostoperativeGrade, combined_MSI_POLE)
laplace_constant = 1
smoothed_countPOLE = countPOLE + laplace_constant
cptPOLEsmoothed = prop.table(smoothed_countPOLE, c(3, 2))

names(dimnames(cptPOLEsmoothed)) = c("POLE", "LNM", "PostoperativeGrade")

fittedModeli$POLE = as.table(cptPOLEsmoothed)

# Compute new FIGO CPT
countFIGO = xtabs(~ FIGO + PostoperativeGrade, combined_FIGO)
laplace_constant = 1
smoothed_countFIGO = countFIGO + laplace_constant
cptFIGOsmoothed = prop.table(smoothed_countFIGO, 2)

names(dimnames(cptFIGOsmoothed)) = c("FIGO", "PostoperativeGrade")

fittedModeli$FIGO = as.table(cptFIGOsmoothed)

```
```{r}

# Plot the Graphs
graphviz.plot(fittedNet, shape = "rectangle", highlight = list("nodes"))
write.net("3. Model/Fitted_Networks/R_WOP_AddTCGA_2_fitted_952+Brno.net", fittedModeli)

```


Now for the third arrangement of the nodes

```{r}
# Define the model string for Dag_1
dag_3 = paste("[MyometrialInvasion|PostoperativeGrade]",#[MRI_MI|MyometrialInvasion]",
            "[Cytology|PostoperativeGrade]",
            "[PreoperativeGrade]",
            "[PostoperativeGrade|PreoperativeGrade]", "[FIGO|PostoperativeGrade]",
            "[LNM|LVSI:MyometrialInvasion:PostoperativeGrade:Chemotherapy]",
            "[CA125|LNM][CTMRI|LNM:CA125]",
            "[LVSI|PostoperativeGrade:Cytology:Chemotherapy]",
            "[p53|LNM:PostoperativeGrade:L1CAM]",
            "[ER|LNM:PostoperativeGrade][PR|LNM:PostoperativeGrade:ER]",
            "[L1CAM|LNM:PostoperativeGrade:PR]",
            "[MSI|LNM:PostoperativeGrade]",
            "[POLE|Recurrence:LNM]",
            "[Recurrence|CA125:LNM:LVSI:PostoperativeGrade]",
            "[Chemotherapy|PostoperativeGrade]",
            "[Radiotherapy|MyometrialInvasion]",
            "[Survival1yr|Recurrence:Chemotherapy:Radiotherapy:Survival3yr:Survival5yr]",
            "[Survival3yr|Recurrence:Chemotherapy:Radiotherapy:Survival5yr]",
            "[Survival5yr|Recurrence:Chemotherapy:Radiotherapy]", sep="")

# dagmodel: pre-defined directed acyclic graph (DAG) structure version 1
dagmodel = model2network(dag_3)

# Plot the Graphs
graphviz.plot(dagmodel, shape = "rectangle", highlight = list("nodes"))


```


Fit the model

```{r}
# Fit the model
fittedModel = bn.fit(dagmodel, data = data, method = 'bayes')
fittedNet = bn.net(fittedModel)
imputedData = impute(fittedModel, data, method = "bayes-lw", n=5000)
fittedModeli = bn.fit(dagmodel, data = imputedData)

```
```{r}
# Load and insert CPTs
combined_MSI_POLE = read.csv("3. Model/CPT_files/MSI_POLE_combined.csv", header = TRUE, sep = ",")
combined_FIGO = read.csv("3. Model/CPT_files/FIGO_combined.csv", header = TRUE, sep = ",")

# Compute new MSI CPT
countMSI = xtabs(~ MSI + LNM + PostoperativeGrade, combined_MSI_POLE)
laplace_constant = 1
smoothed_countMSI = countMSI + laplace_constant
cptMSIsmoothed = prop.table(smoothed_countMSI, c(3, 2))

names(dimnames(cptMSIsmoothed)) = c("MSI", "LNM", "PostoperativeGrade")

fittedModeli$MSI = as.table(cptMSIsmoothed)

# Compute new POLE CPT
countPOLE = xtabs(~ POLE + LNM + PostoperativeGrade, combined_MSI_POLE)
laplace_constant = 1
smoothed_countPOLE = countPOLE + laplace_constant
cptPOLEsmoothed = prop.table(smoothed_countPOLE, c(3, 2))

names(dimnames(cptPOLEsmoothed)) = c("POLE", "LNM", "PostoperativeGrade")

fittedModeli$POLE = as.table(cptPOLEsmoothed)

# Compute new FIGO CPT
countFIGO = xtabs(~ FIGO + PostoperativeGrade, combined_FIGO)
laplace_constant = 1
smoothed_countFIGO = countFIGO + laplace_constant
cptFIGOsmoothed = prop.table(smoothed_countFIGO,2)

names(dimnames(cptFIGOsmoothed)) = c("FIGO", "PostoperativeGrade")

fittedModeli$FIGO = as.table(cptFIGOsmoothed)

```
```{r}


# Plot the Graphs
graphviz.plot(fittedNet, shape = "rectangle", highlight = list("nodes"))
write.net("3. Model/Fitted_Networks/R_WOP_AddTCGA_3_fitted_952.net", fittedModeli)

```



Now for the fourth arrangement of the nodes

```{r}
# Define the model string for Dag_1
dag_4 = paste("[MyometrialInvasion|PostoperativeGrade]",#[MRI_MI|MyometrialInvasion]",
            "[Cytology|PostoperativeGrade]",
            "[PreoperativeGrade]",
            "[PostoperativeGrade|PreoperativeGrade]", "[FIGO|PostoperativeGrade]",
            "[LNM|LVSI:MyometrialInvasion:PostoperativeGrade:Chemotherapy]",
            "[CA125|LNM][CTMRI|LNM:CA125]",
            "[LVSI|PostoperativeGrade:Cytology:Chemotherapy]",
            "[p53|LNM:PostoperativeGrade:L1CAM]",
            "[ER|LNM:PostoperativeGrade][PR|LNM:PostoperativeGrade:ER]",
            "[L1CAM|LNM:PostoperativeGrade:PR]",
            "[MSI|LNM:PostoperativeGrade]",
            "[POLE|Recurrence:LNM:PostoperativeGrade]",
            "[Recurrence|CA125:LNM:LVSI:PostoperativeGrade]",
            "[Chemotherapy|PostoperativeGrade]",
            "[Radiotherapy|MyometrialInvasion]",
            "[Survival1yr|Recurrence:Chemotherapy:Radiotherapy:Survival3yr:Survival5yr]",
            "[Survival3yr|Recurrence:Chemotherapy:Radiotherapy:Survival5yr]",
            "[Survival5yr|Recurrence:Chemotherapy:Radiotherapy]", sep="")

# dagmodel: pre-defined directed acyclic graph (DAG) structure version 1
dagmodel = model2network(dag_4)

# Plot the Graphs
graphviz.plot(dagmodel, shape = "rectangle", highlight = list("nodes"))


```


Fit the model

```{r}
# Fit the model
fittedModel = bn.fit(dagmodel, data = data, method = 'bayes')
fittedNet = bn.net(fittedModel)
imputedData = impute(fittedModel, data, method = "bayes-lw", n=5000)
fittedModeli = bn.fit(dagmodel, data = imputedData)

```
```{r}
# Load and insert CPTs
combined_MSI_POLE = read.csv("3. Model/CPT_files/MSI_POLE_combined.csv", header = TRUE, sep = ",")
combined_FIGO = read.csv("3. Model/CPT_files/FIGO_combined.csv", header = TRUE, sep = ",")

# Compute new MSI CPT
countMSI = xtabs(~ MSI + LNM + PostoperativeGrade, combined_MSI_POLE)
laplace_constant = 1
smoothed_countMSI = countMSI + laplace_constant
cptMSIsmoothed = prop.table(smoothed_countMSI, c(3, 2))

names(dimnames(cptMSIsmoothed)) = c("MSI", "LNM", "PostoperativeGrade")

fittedModeli$MSI = as.table(cptMSIsmoothed)

# Compute new POLE CPT
countPOLE = xtabs(~ POLE + LNM + PostoperativeGrade, combined_MSI_POLE)
laplace_constant = 1
smoothed_countPOLE = countPOLE + laplace_constant
cptPOLEsmoothed = prop.table(smoothed_countPOLE, c(3, 2))

names(dimnames(cptPOLEsmoothed)) = c("POLE", "LNM", "PostoperativeGrade")

fittedModeli$POLE = as.table(cptPOLEsmoothed)

# Compute new FIGO CPT
countFIGO = xtabs(~ FIGO + PostoperativeGrade, combined_FIGO)
laplace_constant = 1
smoothed_countFIGO = countFIGO + laplace_constant
cptFIGOsmoothed = prop.table(smoothed_countFIGO, 2)

names(dimnames(cptFIGOsmoothed)) = c("FIGO", "PostoperativeGrade")

fittedModeli$FIGO = as.table(cptFIGOsmoothed)


```
```{r}

# Plot the Graphs
graphviz.plot(fittedNet, shape = "rectangle", highlight = list("nodes"))
write.net("3. Model/Fitted_Networks/R_WOP_AddTCGA_4_fitted_952.net", fittedModeli)

```