### Author: Ally Sprik
### Last-updated: 25-02-2024

Goal of this notebook is to generate the network without platelets, containing MRI_MI.

```{r}
library(bnlearn)
library(dplyr)
library(Rgraphviz)

# Network postfix
postfix = "952+Brno"

# Define Directed Acyclic Graph (DAG) structure
# It is a string that defines the structure of the Bayesian network according to the following rules:
# [node1|node2:node3] means that node1 is dependent on node2 and node3
# A node must be defined before it can be used as a parent node
# each bracket pair defines a node and its parents
dag = paste("[MyometrialInvasion|PostoperativeGrade][MRI_MI|MyometrialInvasion]",
            "[Cytology|PostoperativeGrade]",
            "[PreoperativeGrade]",
            "[PostoperativeGrade|PreoperativeGrade]",
            "[FIGO|PostoperativeGrade]",
            "[LNM|LVSI:MyometrialInvasion:PostoperativeGrade:Chemotherapy]",
            "[CA125|LNM][CTMRI|LNM:CA125]",
            "[LVSI|PostoperativeGrade:Cytology:Chemotherapy]",
            "[p53|LNM:PostoperativeGrade:L1CAM]",
            "[ER|LNM:PostoperativeGrade][PR|LNM:PostoperativeGrade:ER]",
            "[L1CAM|LNM:PostoperativeGrade:PR]",
            #"[MSI|LNM:PostoperativeGrade]",
            #"[POLE|LNM:PostoperativeGrade]",
            "[Recurrence|CA125:LNM:LVSI:PostoperativeGrade]",
            "[Chemotherapy|PostoperativeGrade]",
            "[Radiotherapy|MyometrialInvasion]",
            "[Survival1yr|Recurrence:Chemotherapy:Radiotherapy:Survival3yr:Survival5yr]",
            "[Survival3yr|Recurrence:Chemotherapy:Radiotherapy:Survival5yr]",
            "[Survival5yr|Recurrence:Chemotherapy:Radiotherapy]", sep="")

#   Convert the string to a graph
dagmodel = model2network(dag)

# Plot the Graphs
graphviz.plot(dagmodel, shape = "rectangle", highlight = list("nodes"))

```
# Import the data and and fit the model

```{r}
# Nodes in the model
nodesDag = names(dagmodel$nodes)

# Import the data
#data = read.csv("0. Source_files/0.2. Cleaned_data/Training+TCGA+JAMA_cleaned.csv", header = TRUE, sep = ",", na.strings = c("NA",
# "N/A", "N/A ", " ", ""))

data = read.csv("0. Source_files/0.2. Cleaned_data/Training_JAMA+Brno_model_complete_cleaned.csv", header = TRUE, sep = ",", na.strings = c("NA", "N/A", "N/A ", " ", ""))

# Select only the rows that have yes in Included_in_training_cohort
#data = data[data$Included_in_training_cohort == "yes",]
# Select for nodes in model
data = as.data.frame(lapply(data[, nodesDag], as.factor))

```

# Fit the model

```{r}
# Fit the model
fittedModel = bn.fit(dagmodel, data = data, method = 'bayes')
# Impute the data
imputedData = impute(fittedModel, data, method = "bayes-lw", n=5000)
# Fit the model again with the imputed data
fittedModeli = bn.fit(dagmodel, data = imputedData)

```


```{r}
# Calculate and insert local CPTs
combined_MRI_MI = read.csv("1. Ally_project/1.3. Model/CPT_files/MRI_MI_combined.csv", header = TRUE, sep = ",")
combined_FIGO = read.csv("1. Ally_project/1.3. Model/CPT_files/FIGO_combined.csv", header = TRUE, sep = ",")

# Compute new MRI CPT
countMRI = table(combined_MRI_MI$MRI_MI, combined_MRI_MI$MyometrialInvasion)
cptMRI = prop.table(countMRI, 2)

names(dimnames(cptMRI)) = c("MRI_MI", "MyometrialInvasion")

# Insert the CPT in the fitted model
fittedModeli$MRI_MI = as.table(cptMRI)

# Compute new FIGO CPT
countFIGO = table(combined_FIGO$FIGO, combined_FIGO$PostoperativeGrade)
cptFIGO = prop.table(countFIGO, 2)

names(dimnames(cptFIGO)) = c("FIGO", "PostoperativeGrade")

# Insert the CPT in the fitted model
fittedModeli$FIGO = as.table(cptFIGO)

# Compute new FIGO CPT
countFIGO = table(combined_FIGO$FIGO, combined_FIGO$PostoperativeGrade)
cptFIGO = prop.table(countFIGO, 2)

names(dimnames(cptFIGO)) = c("FIGO", "PostoperativeGrade")

# Insert the CPT in the fitted model
fittedModeli$FIGO = as.table(cptFIGO)

```

```{r}
# Plot the Graphs
graphviz.plot(fittedNet, shape = "rectangle", highlight = list("nodes"))

# Save the network
url = paste("1. Ally_project/1.3. Model/Fitted_Networks/R_WOP_AddMRIMI_fitted_",postfix,".net", sep="")
write.net(url, fittedModeli)
```


```